# Use root/example as user/password credentials
version: '3.6'
networks:
  my_network:
    driver: bridge

services:
  mongo:
    image: mongo
    networks:
      - my_network
    restart: always
    ports:
      - 27017:27017

