version: '3.6'
networks:
  my_network:
    driver: bridge
    
services:
  mongo:
    image: mongo
    restart: always
    networks:
      - my_network
    ports:
      - 27017:27017

  redis:
    image: redis:6.2-alpine
    networks:
      - my_network
    restart: always
    ports:
      - '6379:6379'